<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
  <TargetFramework>net8.0-windows</TargetFramework>
  <OutputType>WinExe</OutputType>
  <RootNamespace>gg_file_organizer</RootNamespace>
  <UseWPF>true</UseWPF>
  <ImplicitUsings>enable</ImplicitUsings>
  <Nullable>enable</Nullable>
  <ApplicationIcon>Resources\GG_icon.ico</ApplicationIcon>
</PropertyGroup>
  <ItemGroup>
    <Resource Include="Resources\Open_Image.png" />
    <Resource Include="Resources\Ph_button.png" />
    <Resource Include="Resources\Folder_open.png" />
    <Resource Include="Resources\Folder_initial.png" />
    <Resource Include="Resources\Folder_onhover.png" />
    <Resource Include="Resources\folder.png" />
    <Resource Include="Resources\button_clear.png" />
    <Resource Include="Resources\button_copy.png" />
    <Resource Include="Resources\button_verify.png" />
    <Resource Include="Resources\button_delete.png" />
    <Resource Include="Resources\icon.ico" />
    <Resource Include="Resources\GG_icon.ico" />
    <Resource Include="Resources\save_icon.png" />
  </ItemGroup>
</Project>